<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class LeadSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $users = [
            [
            'name' => 'Arun',
            'email' =>  'arun@gmail.com',
            'mobile'=>'9818212276',
            'description'=>'This is a good product i want to more.',
            'source'=>'Website',
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'Dheeru',
            'email' =>  'dheeru@gmail.com',
            'mobile'=>'9818212278',
            'description'=>'This is a good product i want to more.',
            'source'=>'Website',
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'Tej',
            'email' =>  'tej@gmail.com',
            'mobile'=>'9818212279',
            'description'=>'This is a good product i want to more.',
            'source'=>'Website',
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'Tej Prakash',
            'email' =>  'tejprakash@gmail.com',
            'mobile'=>'9818212270',
            'description'=>'This is a good product i want to more.',
            'source'=>'Website',
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'Ayush Chopra',
            'email' =>  'ayush@gmail.com',
            'mobile'=>'9818212210',
            'description'=>'This is a good product i want to more.',
            'source'=>'Website',
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'Anshu',
            'email' =>  'anshu@gmail.com',
            'mobile'=>'9818212212',
            'description'=>'This is a good product i want to more.',
            'source'=>'Website',
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'Sapna',
            'email' =>  'sapna@gmail.com',
            'mobile'=>'9818212213',
            'description'=>'This is a good product i want to more.',
            'source'=>'Website',
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'Sona',
            'email' =>  'sona@gmail.com',
            'mobile'=>'9818212214',
            'description'=>'This is a good product i want to more.',
            'source'=>'Website',
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'Sona Singh',
            'email' =>  'sonasingh@gmail.com',
            'mobile'=>'9818212215',
            'description'=>'This is a good product i want to more.',
            'source'=>'Website',
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'Naveen',
            'email' =>  'naveen@gmail.com',
            'mobile'=>'9818212216',
            'description'=>'This is a good product i want to more.',
            'source'=>'Website',
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'Varun',
            'email' =>  'varun@gmail.com',
            'mobile'=>'9818212217',
            'description'=>'This is a good product i want to more.',
            'source'=>'Website',
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'Neeraj',
            'email' =>  'neeraj@gmail.com',
            'mobile'=>'9818212218',
            'description'=>'This is a good product i want to more.',
            'source'=>'Website',
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'Sudhir Singh',
            'email' =>  'sudhir@gmail.com',
            'mobile'=>'9818212219',
            'description'=>'This is a good product i want to more.',
            'source'=>'Website',
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'Ashish',
            'email' =>  'ashish@gmail.com',
            'mobile'=>'9818212221',
            'description'=>'This is a good product i want to more.',
            'source'=>'Website',
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'Manoj',
            'email' =>  'manoj@gmail.com',
            'mobile'=>'9818212221',
            'description'=>'This is a good product i want to more.',
            'source'=>'Website',
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'Rohit',
            'email' =>  'rohit@gmail.com',
            'mobile'=>'9818212222',
            'description'=>'This is a good product i want to more.',
            'source'=>'Website',
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'Annu',
            'email' =>  'annu@gmail.com',
            'mobile'=>'9818212223',
            'description'=>'This is a good product i want to more.',
            'source'=>'Website',
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'Rahul Singh',
            'email' =>  'rahul@gmail.com',
            'mobile'=>'9818212224',
            'description'=>'This is a good product i want to more.',
            'source'=>'Website',
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'Jyoti',
            'email' =>  'jyoti@gmail.com',
            'mobile'=>'9818212225',
            'description'=>'This is a good product i want to more.',
            'source'=>'Website',
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'Satvik',
            'email' =>  'satvik@gmail.com',
            'mobile'=>'9818212226',
            'description'=>'This is a good product i want to more.',
            'source'=>'Website',
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'Satvik',
            'email' =>  'satvik@gmail.com',
            'mobile'=>'9818212226',
            'description'=>'This is a good product i want to more.',
            'source'=>'Website',
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'Himanshu',
            'email' =>  'himanshu@gmail.com',
            'mobile'=>'9818212227',
            'description'=>'This is a good product i want to more.',
            'source'=>'Website',
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'Vivek',
            'email' =>  'vivek@gmail.com',
            'mobile'=>'9818212228',
            'description'=>'This is a good product i want to more.',
            'source'=>'Website',
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'Munna',
            'email' =>  'munna@gmail.com',
            'mobile'=>'9818212229',
            'description'=>'This is a good product i want to more.',
            'source'=>'Website',
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'Sachin',
            'email' =>  'sachin@gmail.com',
            'mobile'=>'9818212230',
            'description'=>'This is a good product i want to more.',
            'source'=>'Website',
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'Dushyant',
            'email' =>  'dushyant@gmail.com',
            'mobile'=>'9818212231',
            'description'=>'This is a good product i want to more.',
            'source'=>'Website',
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'Prince',
            'email' =>  'prince@gmail.com',
            'mobile'=>'9818212232',
            'description'=>'This is a good product i want to more.',
            'source'=>'Website',
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'Mukesh',
            'email' =>  'mukesh@gmail.com',
            'mobile'=>'9818212233',
            'description'=>'This is a good product i want to more.',
            'source'=>'Website',
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'Lokesh',
            'email' =>  'lokesh@gmail.com',
            'mobile'=>'9818212234',
            'description'=>'This is a good product i want to more.',
            'source'=>'Website',
            'created_at' => now(),
            'updated_at' => now(),
            ],
            [
            'name' => 'Nitin',
            'email' =>  'nitin@gmail.com',
            'mobile'=>'9818212235',
            'description'=>'This is a good product i want to more.',
            'source'=>'Website',
            'created_at' => now(),
            'updated_at' => now(),
            ]
    ];

        foreach ($users as $user) {
                DB::table('leads')->insert($user);
        }
    }

}